name: Deploy User Service to EC2

on:
  push:
    branches:
      - main  # o la rama que uses para producci√≥n
    paths:
      - "users/**"  # solo se ejecuta si cambias algo dentro de user-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Grant execute permission for Gradle wrapper
        working-directory: ./users
        run: chmod +x gradlew

      - name: Build JAR with Gradle
        working-directory: ./users
        run: ./gradlew clean build -x test

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest ./user-service

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
            docker stop user-service || true
            docker rm user-service || true
            docker run -d \
              --name user-service \
              -p 8081:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e AWS_REGION=us-east-1 \
              -e JAVA_OPTS="-Xms256m -Xmx512m" \
              ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
